import paho.mqtt.client as mqtt

client = mqtt.Client(clean_session=True)
# client.tls_set("/Users/saulfranciscoacunagodoy/PycharmProjects/estacion_central/local_credentials/ca.crt", tls_version=2)
# client.tls_insecure_set(True)
client.username_pw_set('station', 'station01')
client.connect("192.168.1.133", 1884, 60)
# client.publish('garden/node/1/air_temperature', 5.4)
# client.publish('garden/node/1/air_humidity', 5.4)
# client.publish('garden/node/1/ground_humidity', 5.4)
# client.publish('garden/node/1/light', 5.4)
# client.publish('garden/node/1/battery_level', 0)
# client.publish('garden/node/1/water', 0)
client.publish('garden/node/1/exc', 1.2, retain=True, qos=1)
client.publish('garden/displayed', b"Hola")
